### ISSUE TITLE
Sofa API generating extra parameters for get calls

### ISSUE THREAD

**Issue by abhijeet1403** [Urigo/SOFA#276] opened 2020-02-04 10:38 UTC
For a typedefinition
![Screenshot from 2020-02-04 16-05-40](https://user-images.githubusercontent.com/16278759/73737274-5109f780-4768-11ea-8bc6-fb91b828bca6.png)
Sofa API generates 
![Screenshot from 2020-02-04 16-03-19](https://user-images.githubusercontent.com/16278759/73737289-5cf5b980-4768-11ea-823d-7218b18363df.png)

**Comment by kamilkisiela** [comment] 2020-02-12 15:15
That's the intended behavior. I will explain it on an example:

```graphql
```

https://codesandbox.io/s/pedantic-pasteur-pbfof?fontsize=14&hidenavigation=1&theme=dark

**Comment by kamilkisiela** [comment] 2020-02-12 15:31
We've got a similar issue posted #153  so I will close this one in favor of #285

**Closed by kamilkisiela** 2020-02-12 15:31 UTC
